server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  main:
    webApplicationType: reactive # I add this configuration because I inherit from parent pom, and it uses the web-starter, so it should put this
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/api/product
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
#logging:
#  level:
#    root: info
#  org:
#    springframework:
#      cloud:
#        gateway-route-RouteDefinitionLocator: info
#        gateway: trace



